using JFramework.Unity;

namespace Game.MyModule
{
    public sealed class ControllerRegistryModule : IModuleInstaller
    {
        public void Install(IServiceRegistry services)
        {
            if (!services.TryResolve<IControllerRegistry>(out _))
                services.AddSingleton<IControllerRegistry>(new ControllerRegistry());

            var controllers = services.Resolve<IControllerRegistry>();

            RegisterControllers(controllers);
        }

        /// <summary>
        /// ע������Controller��ControllerRegistry�У�ControllerRegistry�Ḻ��Controller���������ڹ���������ṩController�Ļ�ȡ�ӿڡ�
        /// </summary>
        /// <param name="controllers"></param>
        void RegisterControllers(IControllerRegistry controllers)
        {
            // <auto-generated-controller-registrations>
            if (!controllers.TryGet<LoginController>(out _)) controllers.Register(new LoginController());

            if (!controllers.TryGet<MatchFightController>(out _)) controllers.Register(new MatchFightController());

            if (!controllers.TryGet<StartFightController>(out _)) controllers.Register(new StartFightController());

            if (!controllers.TryGet<WorkingController>(out _)) controllers.Register(new WorkingController());
// </auto-generated-controller-registrations>
        }
    }
}
