using JFramework.Unity;

namespace Game.MyModule
{

    public sealed class ViewRegistryModule : IModuleInstaller
    {
        public void Install(IServiceRegistry services)
        {


            //ע����ͼ
            if (!services.TryResolve<IViewRegistry>(out _))
                services.AddSingleton<IViewRegistry>(new ViewRegistry());

            var views = services.Resolve<IViewRegistry>();
            // <auto-generated-view-registrations>
            views.RegisterForScene(typeof(SceneLoginState), new BackgroundView());

            views.RegisterForScene(typeof(SceneLoginState), new LoginBackgroundView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelCastleView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelLoginView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelMainBottomView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelNetworkHoldingView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelStartMenuView());

            views.RegisterForScene(typeof(SceneLoginState), new UIPanelWarningMessageView());
// </auto-generated-view-registrations>
        }
    }
}
