using JFramework.Unity;

namespace Game.ProjectA
{
    public sealed class ControllerRegistryModule : IModuleInstaller
    {
        public void Install(IServiceRegistry services)
        {
            if (!services.TryResolve<IControllerRegistry>(out _))
            {
                services.AddSingleton<IControllerRegistry>(new ControllerRegistry());
            }

            var controllers = services.Resolve<IControllerRegistry>();

            // <auto-generated-controller-registrations>
            if (!controllers.TryGet<LoginController>(out _)) controllers.Register(new LoginController());

            if (!controllers.TryGet<MatchFightController>(out _)) controllers.Register(new MatchFightController());

            if (!controllers.TryGet<StartFightController>(out _)) controllers.Register(new StartFightController());
// </auto-generated-controller-registrations>
        }
    }
}
