using JFramework.Unity;

namespace Game.ProjectA
{
    public sealed class SceneRegistryModule : IModuleInstaller
    {
        public void Install(IServiceRegistry services)
        {
            if (!services.TryResolve<ISceneStateRegistry>(out _))
                services.AddSingleton<ISceneStateRegistry>(new SceneStateRegistry());

            var sceneStates = services.Resolve<ISceneStateRegistry>();

            // <auto-generated-scene-state-registrations>
            if (!sceneStates.TryGet<SceneLoginState>(out _)) sceneStates.Register(new SceneLoginState());

            if (!sceneStates.TryGet<SceneMainState>(out _)) sceneStates.Register(new SceneMainState());
// </auto-generated-scene-state-registrations>

            if (!services.TryResolve<GameContext>(out var context))
            {
                context = new GameContext();
                services.AddSingleton(context);
            }

            if (!services.TryResolve<ISceneContext>(out _))
            {
                var sceneContext = new SceneContext(services);
                services.AddSingleton<ISceneContext>(sceneContext);
                services.AddSingleton<IViewContext>(sceneContext);
            }

            if (!services.TryResolve<ISceneFlow>(out _))
            {
                services.AddSingleton<ISceneFlow>(
                    new SceneFlowService(
                        services.Resolve<ISceneStateRegistry>(),
                        services.Resolve<ISceneContext>(),
                        typeof(SceneLoginState)));
            }
        }
    }
}
