using JFramework.Unity;

namespace Game.ProjectA
{
    public sealed class ViewRegistryModule : IModuleInstaller
    {
        public void Install(IServiceRegistry services)
        {
            if (!services.TryResolve<IViewRegistry>(out _))
            {
                services.AddSingleton<IViewRegistry>(new ViewRegistry());
            }

            var views = services.Resolve<IViewRegistry>();

            // <auto-generated-view-registrations>
            var view_LoginBackgroundView = new LoginBackgroundView();

            views.RegisterForScene(typeof(SceneLoginState), view_LoginBackgroundView);

            var view_UIPanelCastleView = new UIPanelCastleView();

            views.RegisterForScene(typeof(SceneMainState), view_UIPanelCastleView);

            var view_UIPanelMainBottomView = new UIPanelMainBottomView();

            views.RegisterForScene(typeof(SceneMainState), view_UIPanelMainBottomView);

            var view_UIPanelStartMenuView = new UIPanelStartMenuView();

            views.RegisterForScene(typeof(SceneMainState), view_UIPanelStartMenuView);

            var view_UIPanelNetworkHoldingView = new UIPanelNetworkHoldingView();

            views.RegisterForScene(typeof(SceneLoginState), view_UIPanelNetworkHoldingView);

            views.RegisterForScene(typeof(SceneMainState), view_UIPanelNetworkHoldingView);

            var view_UIPanelWarningMessageView = new UIPanelWarningMessageView();

            views.RegisterForScene(typeof(SceneLoginState), view_UIPanelWarningMessageView);

            views.RegisterForScene(typeof(SceneMainState), view_UIPanelWarningMessageView);

            var view_UIPanelLoginView = new UIPanelLoginView();

            views.RegisterForScene(typeof(SceneLoginState), view_UIPanelLoginView);
// </auto-generated-view-registrations>
        }
    }
}
